name: Extend
on: 
#  schedule: 
#    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  main:
    name: ExpireAutomaticly
    runs-on: ubuntu-latest
    env:
      CT8users: ${{ secrets.usernames }}
      CT8passwds: ${{ secrets.passwords }}
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
    - name: SetUpDependicies
      run: |
        wget https://github.com/ShadowObj/e3617150-bc5c-44d4-a05d-74fcf6d009ab/raw/main/chrome-linux.zip.001
        wget https://github.com/ShadowObj/e3617150-bc5c-44d4-a05d-74fcf6d009ab/raw/main/chrome-linux.zip.002
        cat chrome-linux.zip.001 chrome-linux.zip.002 > ./chrome-linux.zip
        unzip ./chrome-linux.zip
        export PATH=$PATH:`pwd`/chrome-linux
        pip3 install selenium
        wget -O main.py https://github.com/ShadowObj/e3617150-bc5c-44d4-a05d-74fcf6d009ab/raw/main/main.py
        python3 main.py -u $CT8users -p $CT8passwds
